openapi: "3.0.0"
info:
  title: Documentation for the electronic webstore - S.B. Telecom
  description: Segment about writing documentation
  version: 1.0.1
  contact:
    email: hsharma@mun.ca
    url: "sbtelecom.com"

# servers:
#   - url: "http://localhost:4000/api/v1"
#     description: for localhost -regular
#   - url: "https://localhost:4000/api/v1"
#     description: for localhost -secure

servers:
  - url: "{protocol}://localhost:8000/api"
    description: for localhost
    variables:  
      protocol:
        enum:
          - http
          - https
        default: http  

components: 
  securitySchemes:     
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http       
      scheme: bearer

paths:
  /signup: 
    post:
      tags:
        - String
      summary: Adds a new user to the database
      consumes:
        - application/json
      produces:
        - application/json
      requestBody: 
        required : true
        content:
          application/json :
            schema:  
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string  
                email:
                  type: string
                phoneNumber:
                  type: number
                password:
                  type: string
      responses: 
        200:
          description: "All Good and successful"
          content:
            application/json:
              schema: 
                type: string
        400:
          description: "Bad Request"      
        500:
          description: "Internal Server Error"  

  /signin: 
    get:
      tags:
        - String
      summary: Signin in the website
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: email
          required: true
          in: string
        - name: password
          required: true
          in: string
        
      
      responses: 
        200:
          description: "All Good and successful"
          content:
            application/json:
              schema: 
                type: object
                properties:
                  email:
                    type: string
                  password:
                    type: string
        400:
          description: "Bad Request"      
        500:
          description: "Internal Server Error"         